name: auto Check-in

on:
  schedule:
    - cron: '40 12 * * *'   # 北京时间每天 20:40
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run GLaDOS Check-in
        env:
          GLADOS_COOKIES: ${{ secrets.GLADOS_COOKIES }}
          SERVERCHAN_SENDKEY: ${{ secrets.WECHAT_NOTIFY }}
        run: python checkin.py
